# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSwatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.4'
  # Pods for iOSwatch

  target 'iOSwatchTests' do
    inherit! :search_paths
    # Pods for testing
 pod 'Alamofire', '~> 4.4'
  end

end
